services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    network_mode: host
    volumes:
      - open-webui:/app/backend/data
    restart: always
    environment:
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_UPDATE_PICTURE_ON_LOGIN: true
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      MICROSOFT_CLIENT_TENANT_ID: ${MICROSOFT_CLIENT_TENANT_ID}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  caddy:
    image: caddy:2-alpine
    container_name: open-webui-caddy
    network_mode: host
    volumes:
      - /home/it/certs:/certs:ro
      - /home/it/OpenWebUI/CaddyFile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

volumes:
  open-webui: